{{- range $comp, $values := .Values.windmill -}}
{{- with $values.autoscaling -}}
{{- if .enabled }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: windmill-{{ $comp }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: windmill-{{ $comp }}
  minReplicas: {{ $values.replicas }}
  maxReplicas: {{ $values.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ $values.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
{{- end }}
