apiVersion: apps/v1
kind: Deployment
metadata:
  name: lsp
  labels:
    app: lsp
    chart: {{ template "windmill.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
spec:
  replicas: {{ .Values.windmill.lspReplicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: windmill
  template:
    metadata:
      labels:
        app: windmill
        container: lsp
    spec:
      containers:
        - name: lsp
          image: ghcr.io/windmill-labs/windmill-lsp:{{ .Values.lsp }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
        resources:
{{ toYaml .Values.windmill.lsp.resources | indent 12 }}
    {{- with .Values.windmill.lsp.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.windmill.lsp.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.windmill.lsp.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}                
      securityContext:
        runAsUser: 0
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: lsp
# spec:
#   clusterIP: None
#   ports:
#   - port: 3001
#     protocol: TCP
#     targetPort: 3001
#   selector:
#     app: windmill
#     container: lsp
#   sessionAffinity: None
#   type: ClusterIP
# status:
#   loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: windmill-lsp
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: windmill
    container: lsp
  sessionAffinity: ClientIP
  type: NodePort
status:
  loadBalancer: {}
