apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: windmill
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 8 }}       
{{- end }}   
spec:
  {{ if .Values.ingress.className }}
  ingressClassName: "{{ .Values.ingress.className }}"
  {{ end }}
  rules:
    - http:
        paths:
          - path: /ws/
            pathType: Prefix
            backend:
              service:
                name: windmill-lsp
                port:
                  number: 3001
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: windmill-frontend
                port:
                  number: 8000