{{- if not .Values.windmill.oauthSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oauth-secret
type: Opaque
data:
  oauth.json: {{ .Values.windmill.oauthConfig | toJson | b64enc | quote }}
{{- end }}