apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "windmill.serviceAccountName" . }}
  labels:
    app: {{ template "windmill.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"