apiVersion: v2
name: windmill
type: application
version: 1.2.0
appVersion: 1.87.2
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.3.1
deprecated: false
description: Windmill - Turn scripts into workflows and UIs in minutes
home: https://www.windmill.dev/
icon: https://www.windmill.dev/img/windmill.svg
keywords:
  - windmill
  - scripts
  - flows
  - workflows
  - internal
  - apps
  - open-source
maintainers:
  - email: ruben@windmill.dev
    name: Windmill Team
    url: https://www.windmill.dev/
sources:
  - https://github.com/windmill-labs/windmill-helm-charts.git
